### ISSUE TITLE
Any significant differences to certigo?

### ISSUE THREAD

**Issue by EugenMayer** [pete911/certinfo#21]
Considering the toolkit of certigo https://github.com/square/certigo, which is also written in go (dependency less) is there anything you would say certinfo does different / more?

Thanks!

**Comment by pete911** [comment]
Hi @EugenMayer I just had a look (I wasn't aware of this repo). I started this project, because I couldn't find any tool that can parse cert chains/bundles (it was always combination of commands), also the `openssl x509 ...` output is quite long. Most of the time I just needed to check expiration and if certs belong to each other. I chose go just because that's my preferred language. If I found certigo 2 years ago, most likely this wouldn't have existed.

I had a quick play with the above project and it is indeed very similar, it parses chains/bundles, it can check remote certs (prints tls version as well), ... It even supports DER, JCEKS, PKCS12 which certinfo does not support (I didn't have the need to add it).

So I guess it comes down to preference, which output suits your needs. I built certinfo to solve problems I had:
- check tls version of remote host
- download certs (when you need to trust internal server etc. <- I know this is not the right approach)
- check expiry of certs (I wanted very clear output `--expiry` flag)

It has nothing extra, not many flags, ... it is built with less features but easy to use so I don't have to remember all the flags/combinations.

I hope that this helps and thanks for the link to certigo :) I'll have a proper look later this week.

**Comment by EugenMayer** [comment]
@pete911 thanks for the answer

Certigo can do all this:

- check tls version of remote host
- download certs (when you need to trust internal server etc. <- I know this is not the right approach)
- check expiry of certs (I wanted very clear output --expiry flag)
- It has nothing extra, not many flags, ... it is built with less features but easy to use so I don't have to remember all the flags/combinations.

And it can do it for ldap, ldaps, ldap+tls. It can download, verify, verify self-signed with a given chain and so on.

Do not get me wrong, i'am no way biased or related to certigo - and I need tools for the same reasons you just mentioned.

Anyway, feel free to close this issue anytime, AFAIU certinfo / certigo are very similar. Thanks!

**Comment by pete911** [comment]
@EugenMayer "Do not get me wrong" <- not at all, I appreciate the comment. Certinfo should work for ldap/ldaps/... `certinfo <ldap-host>:636`, ldap is on top of TCP and certinfo uses tcp connection. Certinfo verifies automatically (can be disabled), but you are right it cannot verify against supplied chain.

Please raise issues for ldap(s) if it doesn't work and also if you need and want to add verification agains supplied chain.
I'll close this one, I hope I helped (or made it easier) to decide which tool to use.
