### ISSUE TITLE
How to obtain the root certificate

### ISSUE THREAD

**Issue by deajan** [pete911/certinfo#41]
Hello,

I've stumbled on your page via [this](https://www.reddit.com/r/devops/comments/v4qddc/certificate_ripper_released_tool_to_extract/) reddit sub.

I'm searching a way to rip a whole certificate chain from an url using letsencrypt certificates.
So far, your tool allows me to rip the cert and the intermediate CA, but doesn't show the root CA.
The server is configured with the intermediate certificate and user certificate, and usually browers or curl like programs resolve the root CA using their own trust store.

Can your program resolve the root CA from the trust store and export it with `-pem-only` along the intermediate and user certificates ?

Thank you for your insight.

I've also tried step-cli and openssl, but with no luck.

**Comment by pete911** [comment]
Hi @deajan, sure you can do it this way:
- get local certificates as well (chains) `certinfo -chains -pem-only <host>:443 > tmp_certs.pem`
- remove duplicates (chain usually contains intermediate, or you can have multiple local chains) `certinfo -no-duplicate -pem-only tmp_certs.pem > certs.pem`

Basically, most of the time, server does not return CA. This would be redundant, because you would ignore it anyway. You need to have CA locally so you can verify chain returned by the server. To see your local CAs/chains that are used to verify server cert(s), you just need to use `chains` flag. 
Then you run the second command just to remove any duplicated certs (if the certificate is validated by multiple chains, if the the chains contains intermediate already returned by the server etc. etc.)

Let me know if this worked for you and thanks for using the tool.

**Comment by deajan** [comment]
Thank you for your quick reply.

...That command doesn't work for me.
`certinfo -insecure -chains localhost:443` returns 2 certificates (the ones the server has, ie intermediate and user):
```
[root@my_super_server ~]# ./certinfo -insecure -chains localhost:443
--- [localhost:443 TLS 1.3] ---
Version: 3
Serial Number: 04:1E:3D:BF:D6:48:C1:A9:BA:[...]
Signature Algorithm: ECDSA-SHA384
Type: end-entity
Issuer: CN=E6,O=Let's Encrypt,C=US
Validity
    Not Before: Dec 16 07:43:57 2024 UTC
    Not After : Mar 16 07:43:56 2025 UTC
Subject: CN=SOMERANDOMSERVER.local
DNS Names: SOMERANDOMSERVER.local
IP Addresses:
Authority Key Id: 93:27:46:98:03:A9:51:68:8E:98:D6[...]
Subject Key Id  : DB:9F:1C:9F:65:41:89:D5:81:76:99:[...]
Key Usage: Digital Signature
Ext Key Usage: Server Auth, Client Auth
CA: false

Version: 3
Serial Number: B0:57:3E:91:73:97:27:70:DB:B4:87:CB:3A:45:2B:38
Signature Algorithm: SHA256-RSA
Type: intermediate
Issuer: CN=ISRG Root X1,O=Internet Security Research Group,C=US
Validity
    Not Before: Mar 13 00:00:00 2024 UTC
    Not After : Mar 12 23:59:59 2027 UTC
Subject: CN=E6,O=Let's Encrypt,C=US
DNS Names:
IP Addresses:
Authority Key Id: 79:B4:59:E6:7B:B6:E5:E4:01:73:80:08:88:C8:1A:58:F6:E9:9B:6E
Subject Key Id  : 93:27:46:98:03:A9:51:68:8E:98:D6:C4:42:48:DB:23:BF:58:94:D2
Key Usage: Digital Signature, Cert Sign, CRL Sign
Ext Key Usage: Client Auth, Server Auth
CA: true
```

Whereas using a browser, it resolves the root certificate which is `ISRG Root X1`, not included in the above output:
![image](https://github.com/user-attachments/assets/cdb95836-1900-4dfd-96b0-d5fe22ca6985)

**Comment by pete911** [comment]
ok, it looks like `certinfo` is not loading local CAs. That's why you need to run it with `-insecure` flag. Does it with with other hosts? e.g. `certinfo -chains google.com:443` Is it only localhost that does not load local CA correctly?

**Comment by deajan** [comment]
From the last line of the output `CA: true`, it seems that letsecnrypt E6 identifies itself as a CA ^^

**Comment by deajan** [comment]
I've run the same command from another host that can resolve the server properly so I don't need `--insecure`.
Got the exact same results as above. Any ideas ?

**Comment by pete911** [comment]
CA only means that the basic constrain of the certificate has CA set to true - https://datatracker.ietf.org/doc/html/rfc5280#section-4.2.1.9
You can see that the "Type" is intermediate. You can also see that the Subject and Authority keys do not match (or are both set):
```
Authority Key Id: 79:B4:59:E6:7B:B6:E5:E4:01:73:80:08:88:C8:1A:58:F6:E9:9B:6E
Subject Key Id  : 93:27:46:98:03:A9:51:68:8E:98:D6:C4:42:48:DB:23:BF:58:94:D2
```
This means that the certificate is not root. You are able to run google.com without insecure, because you have root cert locally (it will be printed when you run `-chains` flag). But it looks like it is missing for your localhost root. Is the screenshot you posted from the same host (browser and command line)?

**Comment by deajan** [comment]
I've run the same command from another host that can resolve the server properly so I don't need `--insecure`.
Got the exact same results as above.

The screenshot is from a windows machine, just to proove that there are indeed 3 levels of certs.

Using letsencrypt, it provides a `fullchain.pem` file which contains the intermediate and user cert which I've setup in haproxy. The root CA isn't included in that fullchain.pem file.
Does certinfo actually try to fetch the root certificate if the server doesn't include it in it's CA chain as in this setup ?

**Comment by pete911** [comment]
certinfo does this when you supply port number `<host>:443`:
- establish tcp connection (either tls skip verify or not, depending on `-insecure` flag)
- download certificates presented by the server
- download verified chains used by tcp connection (and print them if `-chains` flag is used)

It looks to me that your cert does not match `localhost` so you need to use `-insecrure` flag. But because validation in case of `-insecure` is not used, no chains are used ...

If this assumption is correct, let me have a look and push "fix" for you.

**Comment by deajan** [comment]
I think you're right. I've added the hostname to `/etc/hosts` to avoid using `-insecure` flag, and voila, I get the full chain.
Perhaps you could implement a `--force-chain-download` or so which would try to verify the chain except the user certificate, but I don't think it makes much sense. That's more a network problem than a tool problem ^^

**Comment by deajan** [comment]
Another thing that perhaps you could work is making `-no-duplicate` work in the initial request, to avoid having to pipe to the same program, ie `./certinfo -chains -pem-only myhost:443 | ./certinfo -no-duplicate -pem-only` would become `./certinfo -chains -pem-only -no-duplicate myhost:443`

**Comment by pete911** [comment]
yes, the `-no-duplicate` to work in the first command is on my list. I'm just working on the insecure fix. I am going to try to load local chain(s) even if the insecure flag is set. I will leave this issue opened until I push the fix.
Thanks for reporting! It is hard to test all these test cases.

**Comment by deajan** [comment]
Sure, just ping me whenever you want me to try a fix. I'm really happy to have found your tool btw, made my day.

**Comment by pete911** [comment]
ok, I pushed the fix. Chains are verified after (not as part of the request). This way I can ignore DNS and time verification. It also works on certificates from files. Pls let me know if this fixes it for you, I will close the issue.
For `-no-duplicate` flag, I need to think about the best approach and will do it as separate commit.

**Comment by pete911** [comment]
@deajan let me know if this works for you, `-insecure -chains` flags work together now. See the post above.

**Comment by deajan** [comment]
Can confirm, works like a charm !
Thank you.
